apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-fwd
  namespace: novusbee
data:
 nginx.conf: |-
    events {}
    http {
        server {
          listen 8080;
            location / {
              proxy_pass http://frontend:80/;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-nginx
  namespace: novusbee
  labels:
    app: ingress-nginx
spec:
  selector:
    matchLabels:
      app: ingress-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: ingress-nginx
    spec:
      imagePullSecrets:
      - name: gitlab-pull-secret
      containers:
        - name: ingress-nginx
          image: nginx:alpine
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: frontend-fwd
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: novusbee
spec:
  ports:
  - name: service
    port: 8080
  selector:
    app: ingress-nginx
