apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator%%TEST%%
  namespace: onlineboutique
spec:
  selector:
    matchLabels:
      app: loadgenerator%%TEST%%
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator%%TEST%%
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging authservice: ${AUTHSERVICE_ADDR}..."
          STATUSCODE=$(wget --server-response http://${AUTHSERVICE_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        name: frontend-check
        image: busybox:latest
        env:
        - name: AUTHSERVICE_ADDR
          value: "authservice:80"
      imagePullSecrets:
      - name: gitlab-pull-secret
      containers:
      - name: main
        image: registry.gitlab.com/novusbee/microservices/loadgenerator:allSuitesV1
        imagePullPolicy: Always
        args:
        - loop
        env:
        - name: AUTHSERVICE_ADDR
          value: "authservice:80"
        - name: USERS
          value: "10"
        resources:
          requests:
            cpu: 300m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi