# Look for the tags __MAKE__CHANGES__FROM__HERE__ and __MAKE__CHANGES__TO__HERE__
name: "Update and deploy breakout"
on:
  push:
    # run on push to branch
    branches:
    - dev--ftr/freeshipping--brkout/freeship003

jobs:
  create-brkout:
    runs-on: [usvcs-runner]
    steps:
    - uses: actions/checkout@v4

    - name: Build deployments
      id: build
      timeout-minutes: 20
      run: |
        # __MAKE__CHANGES__FROM__HERE__
        # place build commands here
        # Build image and push to registry for container 'server' of deployment 'shippingservice'
        cd src/shippingservice
        docker buildx build . -t registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2
        docker push registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2
        echo "IMAGE_shippingservice_server=registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2" >> $GITHUB_OUTPUT
        cd ../..
        
        # __MAKE__CHANGES__TO__HERE__

    - name: Create Breakout
      timeout-minutes: 20
      run: |
        cat <<EOF > breakout.yaml
        apiVersion: appez.rightelast.com/v1beta1
        kind: Breakout
        metadata:
          creationTimestamp: null
          name: freeship003
          namespace: appez-kf1f-j582-l7cf02-m74b882c
        spec:
          application: onlineboutique
          baseBreakout: appez-dflt-brkout
          cluster: clstr-do-001
          environment: dev
          feature: freeshipping
          moduleRefs:
          - containers:
            - buildCommands: |
                cd src/shippingservice
                docker buildx build . -t registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2
                docker push registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2
                echo "IMAGE_shippingservice_server=registry.gitlab.com/novusbee/microservices/shippingservice:varFreeShipv2" >> $GITHUB_OUTPUT
                cd ../..
              env:
              - name: NUM_ITEMS_FOR_FREE_SHIPPING
                value: "003"
              envType: Add
              image: ${{ steps.build.outputs.IMAGE_shippingservice_server }}
              name: server
              resources: {}
            kind: Deployment
            name: shippingservice
          - kind: Service
            name: shippingservice
          routingRules:
            httpRoute: {}
          scope: protected
        status: {}
        EOF
        #
        curl -X PUT https://appez.rightelast.com/api/v1/breakouts -H 'Content-Type: application/x-yaml' --data-binary @breakout.yaml