# Look for the tags __MAKE__CHANGES__FROM__HERE__ and __MAKE__CHANGES__TO__HERE__
name: "Update and deploy breakout"
on:
  push:
    # run on push to branch
    branches:
      - dev--ftr/freeshipping--brkout/freeship003

jobs:
  create-brkout:
    runs-on: [usvcs-runner]
    steps:
    - uses: actions/checkout@v4

    - name: Build deployments
      id: build
      timeout-minutes: 20
      run: |
        # __MAKE__CHANGES__FROM__HERE__
        cd src/shippingservice
        docker buildx build . -t registry.gitlab.com/novusbee/microservices/shippingservice:freeshipV3
        docker push registry.gitlab.com/novusbee/microservices/shippingservice:freeshipV3
        echo "IMAGE_shippingservice_server=registry.gitlab.com/novusbee/microservices/shippingservice:freeshipV3" >> $GITHUB_OUTPUT        
        # __MAKE__CHANGES__TO__HERE__

    - name: Create Breakout
      timeout-minutes: 20
      run: |
        cat <<EOF > breakout.yaml
        apiVersion: appez.rightelast.com/v1beta1
        kind: Breakout
        metadata:
          creationTimestamp: null
          name: freeship003
          namespace: appez--j582--l7cf02--m74b882c
        spec:
          application: onlineboutique
          baseBreakout: dflt--brkout
          clusterName: mykube
          environment: dev
          feature: freeshipping
          moduleRefs:
          - containers:
            - env:
              - name: NUM_ITEMS_FOR_FREE_SHIPPING
                value: "003"
              envType: Add
              image: ${{ steps.build.outputs.IMAGE_shippingservice_server }}
              livenessProbe:
                exec:
                  command:
                  - /bin/grpc_health_probe
                  - -addr=:50051
                failureThreshold: 10
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 30
              livenessProbeType: Replace
              name: server
              readinessProbe:
                exec:
                  command:
                  - /bin/grpc_health_probe
                  - -addr=:50051
                failureThreshold: 10
                periodSeconds: 30
                successThreshold: 1
                timeoutSeconds: 30
              readinessProbeType: Replace
              resources:
                limits:
                  cpu: 35m
                  memory: 35Mi
                requests:
                  cpu: 25m
                  memory: 25Mi
            kind: Deployment
            name: shippingservice
          - kind: Service
            name: shippingservice
          routingRules:
            httpRoute:
              rules:
              - matches:
                - headers:
                  - name: Tenantname
                    type: Exact
                    value: Tenant003
          scope: public
        status: {}
        EOF
        
        curl -X PUT http://appez-api.rightelast.com:20082/api/breakouts -H 'Content-Type: application/x-yaml' --data-binary @breakout.yaml
