# Look for the tags __MAKE__CHANGES__FROM__HERE__ and __MAKE__CHANGES__TO__HERE__
name: "Update and deploy breakout"
on:
  pull_request:
    # run on pull request from branch
    types:
    - opened
    - edited
    - reopened
    - synchronize

jobs:
  test-print:
    runs-on: [usvcs-runner]
    steps:
    - name: Test print github variable
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo ${{ github.head_ref }}
        echo "$GITHUB_CONTEXT"

  create-brkout:
    needs:
    - test-print
    if: endsWith(github.head_ref, 'dev--ftr/showrecos--brkout/showrecos-brkout1') && github.event_name == 'pull_request' && github.event.action == 'synchronize'
    runs-on: [usvcs-runner]
    steps:
    - uses: actions/checkout@v4

    - name: Build deployments
      id: build
      timeout-minutes: 20
      run: |
        # place build commands here
        cd src/recommendationservice/
        docker buildx build . -t registry.gitlab.com/novusbee/microservices/recommendationservice:showrecos
        docker push registry.gitlab.com/novusbee/microservices/recommendationservice:showrecos
        cd ../..
        echo "IMAGE_recommendationservice_server=registry.gitlab.com/novusbee/microservices/recommendationservice:showrecos" >> $GITHUB_OUTPUT

    - name: Create Breakout
      timeout-minutes: 20
      run: |
        cat <<EOF > breakout.yaml
        apiVersion: appez.rightelast.com/v1beta1
        kind: Breakout
        metadata:
          creationTimestamp: null
          name: showrecos-brkout1
          namespace: appez-kb51-j582-l7cf02-m7dff987
        spec:
          application: onlineboutique
          baseBreakout: appez-dflt-brkout
          cluster: clstr0001
          environment: dev
          feature: showrecos
          moduleRefs:
          - containers:
            - image: ${{ steps.build.outputs.IMAGE_recommendationservice_server }}
              name: server
              resources: {}
            kind: Deployment
            name: recommendationservice
          - kind: Service
            name: recommendationservice
          routingMode: basic
          routingRules:
            httpRoute: {}
          scope: public
        status: {}
        EOF
        #
        curl -X PUT https://appez-api.rightelast.com/api/v1/breakouts -H 'Content-Type: application/x-yaml' --data-binary @breakout.yaml