# Look for the tags __MAKE__CHANGES__FROM__HERE__ and __MAKE__CHANGES__TO__HERE__
name: "Pull request create from breakout to parent"
on:
  pull_request:
    types:
    - closed
    # run on pull request from breakout branch

env:
  brkoutName: pr-${{ github.event.number }}

concurrency:
  group: pr-merge-to-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
 
jobs:
  pr-merge:
    runs-on: [kubefocus-org]
    if: ${{ github.head_ref == 'c/pcs-e/p4-f/g858l-b/69' && github.event.pull_request.merged == true && contains(toJson(github.event.pull_request.labels.*.name), 'breakout') }}
    steps:
    - name: Checkout merged base branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.ref }}

    - name: Show git status
      run: |
        echo "Base branch: ${{ github.event.pull_request.base.ref }}"
        git log -1 --oneline

    - name: Build deployments
      id: build
      timeout-minutes: 20
      run: |
        echo "$brkoutName"
        # __MAKE__CHANGES__FROM__HERE__

        # place build commands here
        # Build image and push to registry for container 'server' of deployment 'shippingservice'
        tag=$(git rev-parse --short=8 HEAD)
        cd src/shippingservice
        docker buildx build . -t registry.gitlab.com/novusbee/microservices/shippingservice:${tag}
        docker push registry.gitlab.com/novusbee/microservices/shippingservice:${tag}
        echo "IMAGE_shippingservice_server=registry.gitlab.com/novusbee/microservices/shippingservice:${tag}" >> $GITHUB_OUTPUT
        cd ../..
        
        # __MAKE__CHANGES__TO__HERE__

    - name: Update Container Images
      timeout-minutes: 20
      run: |
        at=$(curl --silent -X POST https://appez-keycloak.kubefocus.com/realms/kubefocus.com/protocol/openid-connect/token   -d grant_type=client_credentials   -d client_id=${{secrets.KC_CLIENT_ID}} -d client_secret=${{ secrets.KC_CLIENT_SECRET }} -d scope=openid | jq -r '.access_token')
        tgtResult=$(curl -s -H 'accept: application/json' -H "X-Auth-Bearer-Token: ${at}" -H 'content-type: application/json' 'https://appez.kubefocus.com/api/v1/breakouts/detail?organization=kubefocus.com&cluster=do1&environment=dev&application=microservices&feature=freeshipping&breakout=appez-dflt-brkout&includeStatus=true' 2> /dev/null)
        srcResult=$(curl -s -H 'accept: application/json' -H "X-Auth-Bearer-Token: ${at}" -H 'content-type: application/json' 'https://appez.kubefocus.com/api/v1/breakouts/detail?organization=kubefocus.com&cluster=do1&environment=dev&application=microservices&feature=freeshipping&breakout=fs&includeStatus=true' 2> /dev/null)
        echo "Current target moduleRefs"
        echo $tgtResult | jq -r '.spec.moduleRefs'
        echo "Current source moduleRefs"
        echo $srcResult | jq -r '.spec.moduleRefs'
        result=$(jq --argjson srcRefs "$(jq -r '.spec.moduleRefs' <<< "$srcResult")"  '.spec.moduleRefs = $srcRefs' <<< "$tgtResult")
        echo $result | jq > breakout.json
        echo "After replace of target moduleRefs"
        cat breakout.json

        result=$(echo $result | jq '.spec.moduleRefs |= map(
          if .kind == "Deployment" and .name == "shippingservice" then
            .containers |= map(
              if .name == "server" then
                .image = "${{ steps.build.outputs.IMAGE_shippingservice_server }}"
              end
            )
          end
        )')

        echo $result | jq -r '.spec.moduleRefs'

        echo $result | jq -r '.spec.moduleRefs'
        echo $result | jq > breakout.json
        echo "Final target breakout spec"
        cat breakout.json

    - name: Update Breakout
      timeout-minutes: 20
      run: |
        at=`curl --silent -X POST https://appez-keycloak.kubefocus.com/realms/kubefocus.com/protocol/openid-connect/token   -d grant_type=client_credentials   -d client_id=${{secrets.KC_CLIENT_ID}} -d client_secret=${{ secrets.KC_CLIENT_SECRET }} -d scope=openid | jq -r '.access_token'`
        curl -X PUT https://appez.kubefocus.com/api/v1/breakouts -H "X-Auth-Bearer-Token: ${at}" -H 'Content-Type: application/json' --data-binary @breakout.json
