name: Check PR Labels

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  check-label:
    runs-on: [kubefocus-org]
    steps:
      - name: Check for label
        if: contains(join(github.event.pull_request.labels.*.name, ','), 'breakout')
        run: echo "PR has the 'breakout' label!"
